In [215]:
#based on the video tutorial: https://www.youtube.com/watch?v=QUT1VHiLmmI&t=24s&ab_channel=freeCodeCamp.org

In [214]:
import numpy as np

# The basics

In [16]:
a = np.array([1,2,3])

In [18]:
b = np.array([3,1,2])

In [19]:
a*b

array([3, 2, 6])

In [21]:
a = np.array([123])
a

array([123])

In [31]:
b = np.array([[1,2,3],[2,3,4],[5,6,7]])
b

array([[1, 2, 3],
       [2, 3, 4],
       [5, 6, 7]])

In [32]:
# Get the dimension of a ndarray
b.ndim

2

In [33]:
c = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],  # First 2D slice
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],  # Second 2D slice
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]   # Third 2D slice
])

print(c)
print("Number of dimensions:", c.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
Number of dimensions: 3


In [79]:
d = np.array([

    [[1,2,3],
    [4,5,6]],

    [[1,2,3],
    [4,5,6]],

    [[1,2,3],
    [4,5,6]]


             ], dtype='int8')

d.ndim

3

In [80]:
#Get the shape of a ndarray
b.shape

(3, 3)

In [81]:
#Get the type
d.dtype

dtype('int8')

In [82]:
d.itemsize

1

In [83]:
#Get total size
d.size * d.itemsize

18

In [84]:
#Get total size
d.nbytes

18

# Accesing / Changing specific elements, rows, columns, etc

In [88]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]], dtype='int8')
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int8)

In [89]:
#Get a specific element [row, column]
a[1,5]

np.int8(13)

In [91]:
#get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7], dtype=int8)

In [92]:
#get a specific column
a[:,2]

array([ 3, 10], dtype=int8)

In [94]:
#getting elements (fancy mode) [row,startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6], dtype=int8)

In [99]:
#getting elements (fancy mode) [row,startindex:endindex:stepsize]
a[1,1:8:1]

array([ 9, 10, 11, 12, 13, 14], dtype=int8)

In [102]:
#update individual values from a ndarray array_name[row,value_position]
a[1,5] = 25

In [110]:
#modify multiple numbers array_name[starting row, last row number] = value to insert
a[:,1] = 25

In [111]:
a

array([[ 1, 25,  3,  4,  5,  6,  7],
       [ 8, 25, 10, 11, 12, 25, 14]], dtype=int8)

In [123]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]], dtype='int8')

In [124]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int8)

In [125]:
#Get a specific element (work from outside to inside)
b[1,0,1]

np.int8(6)

In [126]:
b[:,0,:]

array([[1, 2],
       [5, 6]], dtype=int8)

In [127]:
#replace values
b[:,0,:] = [[9,8],[7,6]]

In [128]:
b

array([[[9, 8],
        [3, 4]],

       [[7, 6],
        [7, 8]]], dtype=int8)

## Initializing different types of Arrays

In [144]:
#zeros matrix
a = np.zeros((2,2,4,2))

In [145]:
a

array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [156]:
#one's matrix
b = np.ones((3,1,4))

In [157]:
b

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [160]:
#Any other number matrix
c = np.full((2,2,2), 80)

In [161]:
c

array([[[80, 80],
        [80, 80]],

       [[80, 80],
        [80, 80]]])

In [163]:
#Any other number (full_like) -> utiliza la forma de otro array previamente generado y remplaza sus numeros
np.full_like(c, 7)

array([[[7, 7],
        [7, 7]],

       [[7, 7],
        [7, 7]]])

In [165]:
#Random decimal numbers
np.random.rand(4,2,3)

array([[[0.9748362 , 0.72245276, 0.33413354],
        [0.95517478, 0.82729006, 0.76715701]],

       [[0.17941688, 0.24632288, 0.84109947],
        [0.48182998, 0.08948257, 0.14285714]],

       [[0.54960704, 0.60336384, 0.46852885],
        [0.02868619, 0.65969856, 0.27993762]],

       [[0.14844717, 0.12745971, 0.27796581],
        [0.54003757, 0.27951791, 0.56913553]]])

In [178]:
#Random integer values (maximal random number, size(shape))
np.random.randint(11, size=(3,4))

array([[10,  8,  7,  7],
       [ 2,  0,  6,  3],
       [ 7,  1,  6,  0]], dtype=int32)

In [181]:
#Random integer values (minimum possible random value, maximal random number, size(shape))
np.random.randint(9,11, size=(3,4))

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [ 9, 10,  9,  9]], dtype=int32)

In [184]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [190]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 5, axis=0)


In [191]:
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [192]:
#excercise how to create a specific array
output = np.ones([5,5])

In [193]:
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [207]:
zeros = np.zeros([3,3])

In [208]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [209]:
zeros[1,1] = 9

In [210]:
zeros

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [212]:
output[1:4,1:4] = zeros #it also works with output[1:-1,1:-1] = zeros

In [213]:
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [220]:
# Be carefully when copying arrays

In [221]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)

[100   2   3]


In [222]:
# To prevent this I can use the copy function

In [238]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematics

In [231]:
a = np.array([1,2,3,4])

In [232]:
a + 2

array([3, 4, 5, 6])

In [233]:
a - 2

array([-1,  0,  1,  2])

In [234]:
a * 2

array([2, 4, 6, 8])

In [235]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [236]:
b = np.array([1,0,1,0])

In [237]:
a + b

array([2, 2, 4, 4])

In [239]:
a ** 2

array([1, 4, 9])

In [240]:
#Take the sin
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [241]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 ])

# Linear Algebra

In [242]:
a = np.ones((2,3))
print(a)
b = np.full((3,2), 2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

# Statistics

In [243]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [244]:
np.min(stats)

np.int64(1)

In [248]:
np.max(stats)

np.int64(6)

In [249]:
np.sum(stats)

np.int64(21)

# Reorganizing arrays

In [253]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [255]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [257]:
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [259]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])